# Generated by Django 5.1.6 on 2025-10-04 20:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigTimbradoNumeracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_timbrado', models.CharField(max_length=100, unique=True)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(default=django.utils.timezone.now)),
                ('nro_inicial', models.IntegerField()),
                ('nro_final', models.IntegerField(null=True)),
                ('nro_actual', models.IntegerField(default=0)),
                ('fecha_insercion', models.DateTimeField(default=django.utils.timezone.now)),
                ('establecimiento', models.IntegerField(default=1)),
                ('punto_expedicion', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ramo_actividad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('fecha_insercion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nro_documento', models.CharField(max_length=100, unique=True)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('estado_civil', models.CharField(choices=[('Casado/a', 'Casado/a'), ('Viudo/a', 'Viudo/a'), ('Soltero/a', 'Soltero/a')], max_length=30)),
                ('codigo_pais', models.CharField(choices=[('+595', 'Paraguay (+595)'), ('+54', 'Argentina (+54)'), ('+55', 'Brasil (+55)'), ('+1', 'Estados Unidos/Canadá (+1)'), ('+34', 'España (+34)'), ('+49', 'Alemania (+49)'), ('+33', 'Francia (+33)'), ('+39', 'Italia (+39)'), ('+81', 'Japón (+81)'), ('+86', 'China (+86)'), ('+91', 'India (+91)'), ('+52', 'México (+52)'), ('+56', 'Chile (+56)'), ('+57', 'Colombia (+57)'), ('+58', 'Venezuela (+58)'), ('+51', 'Perú (+51)'), ('+598', 'Uruguay (+598)'), ('+591', 'Bolivia (+591)')], default='+595', help_text='Código de país para el teléfono', max_length=5)),
                ('num_tel', models.CharField(help_text='Número de teléfono sin código de país', max_length=15, validators=[django.core.validators.RegexValidator(message='Ingrese solo números, entre 6 y 12 dígitos.', regex='^\\d{6,12}$')])),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('fecha_insercion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('tipo_documento', models.CharField(choices=[('RUC', 'RUC'), ('CI', 'CI')], max_length=100)),
            ],
            options={
                'unique_together': {('codigo_pais', 'num_tel')},
            },
        ),
        migrations.CreateModel(
            name='VentaCabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now)),
                ('nro_comprobante', models.CharField(max_length=100, unique=True)),
                ('condicion_venta', models.CharField(max_length=100)),
                ('timbrado', models.CharField(max_length=100)),
                ('nota_remision', models.CharField(max_length=100, null=True)),
                ('vendedor', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('forma_pago', models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('TRANSFERENCIA', 'TRANSFERENCIA')], max_length=100)),
                ('iva_diez', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_cinco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_insercion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('descripcion', models.TextField(null=True)),
                ('unidad_medida', models.CharField(max_length=100, null=True)),
                ('precio_unit_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_insercion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.producto')),
                ('venta_cab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.ventacabecera')),
            ],
        ),
    ]
