# Generated by Django 5.1.6 on 2025-09-29 17:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_insercion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompraCab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_comprobante', models.CharField(max_length=100, unique=True)),
                ('fecha_compra', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=100)),
                ('forma_pago', models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('TRANSFERENCIA', 'TRANSFERENCIA')], max_length=100)),
                ('fecha_insercion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_diez', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_cinco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=100)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=100)),
                ('iva', models.IntegerField(choices=[(10, 10), (5, 5)], default='10')),
                ('cantidad_en_stock', models.IntegerField()),
                ('fecha_insercion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('unidad_medida', models.CharField(choices=[('METROS', 'METROS'), ('UNIDADES', 'UNIDADES'), ('KILOGRAMOS', 'KILOGRAMOS'), ('LITROS', 'LITROS'), ('CAJAS', 'CAJAS'), ('PAQUETES', 'PAQUETES')], max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompraDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad', models.IntegerField()),
                ('unidad_medida', models.CharField(choices=[('METROS', 'METROS'), ('UNIDADES', 'UNIDADES'), ('KILOGRAMOS', 'KILOGRAMOS'), ('LITROS', 'LITROS'), ('CAJAS', 'CAJAS'), ('PAQUETES', 'PAQUETES')], max_length=100)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=100)),
                ('total_producto', models.DecimalField(decimal_places=2, max_digits=100)),
                ('fecha_insercion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('orden_compra_cab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.ordencompracab')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=50, unique=True)),
                ('representante', models.CharField(blank=True, max_length=50)),
                ('nro_documento', models.CharField(max_length=30, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_pais', models.CharField(choices=[('+595', 'Paraguay (+595)'), ('+54', 'Argentina (+54)'), ('+55', 'Brasil (+55)'), ('+1', 'Estados Unidos/Canadá (+1)'), ('+34', 'España (+34)'), ('+49', 'Alemania (+49)'), ('+33', 'Francia (+33)'), ('+39', 'Italia (+39)'), ('+81', 'Japón (+81)'), ('+86', 'China (+86)'), ('+91', 'India (+91)'), ('+52', 'México (+52)'), ('+56', 'Chile (+56)'), ('+57', 'Colombia (+57)'), ('+58', 'Venezuela (+58)'), ('+51', 'Perú (+51)'), ('+598', 'Uruguay (+598)'), ('+591', 'Bolivia (+591)')], default='+595', help_text='Código de país para el teléfono', max_length=5)),
                ('num_tel', models.CharField(help_text='Número de teléfono sin código de país', max_length=15, validators=[django.core.validators.RegexValidator(message='Ingrese solo números, entre 6 y 12 dígitos.', regex='^\\d{6,12}$')])),
                ('correo', models.EmailField(max_length=30, unique=True)),
                ('fecha_insercion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_documento', models.CharField(choices=[('RUC', 'RUC'), ('CI', 'CI')], max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('codigo_pais', 'num_tel')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor'),
        ),
        migrations.AddField(
            model_name='ordencompracab',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor'),
        ),
    ]
