# Generated by Django 5.1.6 on 2025-10-04 20:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_maxima', models.IntegerField(default=3)),
                ('descripcion', models.CharField(default='Configuración de stock', max_length=255)),
                ('fecha_configuracion', models.DateTimeField(default=django.utils.timezone.now)),
                ('frecuencia_notificacion', models.PositiveIntegerField(default=1800)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ajuste', models.CharField(choices=[('DEVOLUCION', 'DEVOLUCION'), ('PERDIDA', 'PERDIDA'), ('DETERIORO', 'DETERIORO'), ('VENCIDO', 'VENCIDO'), ('EXTRAVIO', 'EXTRAVIO'), ('RECLAMO', 'RECLAMO'), ('REPOSICION', 'REPOSICION'), ('OTRO', 'OTRO')], max_length=10, null=True)),
                ('movimiento', models.CharField(choices=[('ENTRADA', 'ENTRADA'), ('SALIDA', 'SALIDA')], max_length=10)),
                ('cantidad_inicial', models.IntegerField()),
                ('cantidad_actual', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('fecha_movimiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.ordencompracab')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.producto')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.ventacabecera')),
            ],
        ),
    ]
